name: Android CI

on:
  pull_request:
    branches: [ master ]


jobs:
  setup:
    uses: ./.github/workflows/common-workflow.yml
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 Run Tests
        run: ./gradlew test

      - name: 🛠 Build Project with Spotless Check
        run: ./gradlew spotlessCheck

      - name: ⏳ Build with Gradle
        run: ./gradlew build

      - name: 🏗 Build APK
        run: bash ./gradlew assembleProductionDebug

      - name: 🚀 Upload APK 📱
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/production/debug/*.apk
          retention-days: 3
