
name: Common Worflow

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path:  |
            ~/.gradle/caches
            ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

      - uses: actions/checkout@v1

      - name: 🧱 Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Grant Gradlew rights
        run: chmod +x gradlew