name: Create APK from Master

on:
  push:
    branches:
    - master

jobs:
  setup:
    uses: ./.github/workflows/common-workflow.yml
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      
    - name: Build APK ⚙️🛠
      run: bash ./gradlew assembleStagingDebug
 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest-master"
          prerelease: true
          title: "Staging Build"
          files: app/build/outputs/apk/staging/debug/*.apk
