name: PR Check

on:
  pull_request:
    types: [ ready_for_review ]
  issue_comment:                                     
    types: [created, edited, deleted]


jobs:

  validatePr: 
   name: 'Validate PR comment'
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [re-centos7]
   steps:
    - name: test
      if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
      run: |
        echo test
 
  spotless:
    needs: validatePr
    name: 'Spotless'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
    
      - name: Setting up project
        uses: ./.github/actions/setup
        
      - name: 🛠 Build Project with Spotless Check
        run: ./gradlew spotlessCheck
        
  tests:
    name: 'Tests'
    needs: validatePr
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
    
      - name: Setting up project
        uses: ./.github/actions/setup
        
      - name: 🧪 Run Tests
        run: ./gradlew test

  build:
    name: 'Build Production Debug Build'
    needs: validatePr
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
    
      - name: Setting up project 
        uses: ./.github/actions/setup

      - name: 🏗 Build With gradle
        run: bash ./gradlew build

      - name: 🏗 Build APK
        run: bash ./gradlew assembleProductionDebug

      - name: 🚀 Upload APK 📱
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/production/debug/*.apk
          retention-days: 3
